import React from 'react';
import './../components/Pages/PolicyPage.css';

export default function TermsPage() {
  return (
    <div className="policy-page">
      <section className="aboutt-hero">
        <div className="overlay">
          <h1>Terms & Conditions</h1>
        </div>
      </section>

      <div className="policy-container">
        <p><em>Last updated: 22/11/2025</em></p>

        <p>
          These Terms & Conditions (“Terms”) govern your use of the Tred Flooring website (“Site”) operated by Tred Flooring Pty Ltd (“Tred”, “we”, “us”, “our”). By using this Site, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use our Site.
        </p>

        <h3>1. Who can use this website</h3>
        <p>Our website is available for general public use. You do not need an account to browse or submit enquiries. Administrative login access is restricted exclusively to authorised Tred employees.</p>

        <h3>2. Information you submit</h3>
        <p>When you submit a form through our Site, you agree that:</p>
        <ul>
          <li>The information you provide (name, email, phone number, project details, etc.) is accurate and complete.</li>
          <li>You will not submit unlawful, harmful, offensive or misleading information in text fields.</li>
          <li>You are responsible for any project information you voluntarily include in your enquiry.</li>
        </ul>
        <p>
          Tred Flooring only receives the information submitted through the form fields. We do not receive, store, access or review any photos used within the AI tool. We reserve the right to remove or restrict any text-based information that violates these Terms or applicable laws.
        </p>

        <h3>3. AI tool – photo uploads</h3>
        <p>Our website includes an optional visualisation tool powered by a third-party AI provider. This tool allows you to upload a photo of your space to preview flooring options. When using this tool, you understand and agree that:</p>
        <ul>
          <li>The photo you upload is processed directly by the AI provider, not by Tred Flooring.</li>
          <li>Tred Flooring does not store, access, view, download, or retain any images uploaded to the AI tool.</li>
          <li>Image processing may be handled temporarily on external servers solely to generate your visualisation.</li>
          <li>You confirm that you have rights to use the photo (for example, it is your home or you have permission).</li>
          <li>The file must not contain viruses, malware or harmful content.</li>
        </ul>
        <p>We are not responsible for: The output generated by the AI tool; the storage or handling of images by the AI provider; system failures, processing delays or technical issues related to the AI service. The AI feature is provided as-is for visualisation purposes only and does not replace showroom verification of colours, textures or materials.</p>

        <h3>4. Intellectual property</h3>
        <p>All content on this website, including logos, designs, photos, product descriptions, graphics, layout, brand elements and written text, is the exclusive property of Tred Flooring unless otherwise stated. You may not:</p>
        <ul>
          <li>Copy</li>
          <li>Reproduce</li>
          <li>Republish</li>
          <li>Edit</li>
          <li>Distribute</li>
          <li>Use commercially</li>
        </ul>
        <p>any part of the Site without written consent from Tred Flooring. Violation of intellectual property rights may result in legal action.</p>

        <h3>5. Accuracy of information</h3>
        <p>We strive to provide up-to-date and accurate information. However:</p>
        <ul>
          <li>Colours may vary based on display screens</li>
          <li>Product specifications may change</li>
          <li>Stock availability can fluctuate</li>
          <li>Photos are illustrative and may differ from final materials</li>
        </ul>
        <p>Tred is not liable for errors, omissions or outdated information on the website. Please visit our showroom to confirm selections before making final decisions.</p>

        <h3>6. Limitation of liability</h3>
        <p>To the maximum extent permitted by law: Tred is not liable for damages resulting from your use or inability to use the website. We do not guarantee the website will be error-free, uninterrupted or secure. We are not responsible for loss or damage caused by outages, hosting failures or third-party tools (Vercel, Render, MongoDB, analytics providers, etc.). We are not responsible for user-uploaded content. Your use of the website is at your own risk.</p>

        <h3>7. Analytics, tracking and cookies</h3>
        <p>Our Site may use third-party tools including:</p>
        <ul>
          <li>Google Analytics</li>
          <li>Meta Pixel</li>
          <li>TikTok Pixel</li>
          <li>Hotjar</li>
        </ul>
        <p>These tools collect anonymous behavioural data to help us improve performance and marketing effectiveness. By using the website, you consent to this tracking. You may disable cookies in your browser at any time.</p>

        <h3>8. Third-party links</h3>
        <p>Our Site may contain links to other websites. We are not responsible for their content, privacy practices or terms.</p>

        <h3>9. Availability and technical issues</h3>
        <p>We do not guarantee continuous uptime. The website may experience outages due to hosting failures, deployment issues, database errors, maintenance, or third-party provider downtime. Tred is not liable for any loss resulting from technical interruptions.</p>

        <h3>10. Changes to these Terms</h3>
        <p>We may update these Terms at any time. The “Last updated” date reflects the current version.</p>

        <h3>11. Contact us</h3>
        <p>
          For questions about these Terms, contact:<br />
          Email: info@tredflooring.com.au<br />
          Address: Supa Centa Moore Park, Ground Floor, 2a Todman Ave, Kensington
        </p>
      </div>
    </div>
  );
}

